/**
 * Generated by geromedev
 * @author Gerónimo Mercante
 */

export const appConfig = {
  name: 'Biblioteca Yenny',
  version: '0.1.0',
  author: 'Gerónimo Mercante, Gianfranco Andreachi, Axel Berger',
  MAIL_ADDRESS: 'mercantegero@gmail.com',
  CURRENCY_SYMBOL: '$',
  CURRENCY_TITLE: 'Pesos ARS',
};
