/**
 * Generated by geromedev
 * @author Gerónimo Mercante
 */

export const appConfig = {
  name: 'Biblioteca Yenny',
  version: '0.1.0',
  author: 'Gerónimo Mercante, Gianfranco Andreachi, Axel Berger',
  MAIL_ADDRESS: 'mercantegero@gmail.com',
  CURRENCY_SYMBOL: '$',
  CURRENCY_TITLE: 'Pesos ARS',
  API_URL: "http://localhost:5000/api/v1",
  DEFAULT_PAGE_NUMBER: 0,
  DEFAULT_PAGE_SIZE: 10
};
