"""Add sales and sale_details tables

Revision ID: 55f5dbf1e00b
Revises: e9dc153bb666
Create Date: 2024-11-17 23:07:48.874263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f5dbf1e00b'
down_revision = 'e9dc153bb666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
